version: '3'
services:
  #service name
    api-gateway:
      container_name: api-gateway
      restart: always
      build: ./api-gateway
      ports:
        - '5050:5050'
      links: 
          - api-posts
          - api-users
    api-posts:
        container_name: user-api
        restart: always
        build: ./user-api
        ports:
          - '4040:4040'
        links: 
            - db-user
    #service name
    api-users:
      container_name: post-api
      restart: always
      build: ./post-api
      ports:
        - '4041:4041'
      links: 
          - db-post
    # run a docker hub image
    # api-auth:
    #   image: diegomezg/api-image
    #   restart: always
    #   build:
    #     dockerfile: dockerfile
    #     context: .
    #   ports:
    #     - '4001:4001'
    #service name, use this for the mongodb connection
    #'mongodb://db-user/dbname'
    # ports are changed but you can use 27017:27017
    # when you use a service connection the port is assigned
    # Example:
    # db-user is docker-compose variable for
    # service_local_host:port
    db-user:
        image: mongo
        ports:
          - '27018:27017'
    #service name
    db-post:
      image: mongo
      ports:
        - '27019:27017'